[package]
Token name = "$CIG"
version = "SOL"
description = "A Rust library for reading and writing WARC files.
"
readme = "README.md"
repository = "https://github.com/jedireza/warc"
documentation = "https://docs.rs/crate/warc/"
license = "MIT"
authors = ["Reza Akhavan <reza@akhavan.me>"]
keywords = ["warc", "web", "archive"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
nom = "5.1.1"
url = "2"
uuid = { version = "0.8.1", features = ["v4"] }

[dependencies.libflate]
version = "1"
optional = true

[dependencies.serde]
version = "1"
optional = true
features = ["derive"]

[features]
default = ["gzip"]
gzip = ["libflate"]
with_serde = ["serde"]
